### ISSUE TITLE
[Feature request] Dynamic format selection

### ISSUE THREAD

**Issue by kitce** [d0u9/youtube-dl-webui#11]
Sometimes I want the complete video, sometimes I only want the audio, also different video/audio qualities.

It would be great if I can select the format from the webUI instead of being hardcoded in the configuration file.

**Comment by d0u9** [comment]
This feature will be added in the next release. You will have a chance to set different configuration for each task before downloading.

**Comment by d0u9** [comment]
I have added this feature in the latest release. You can specify the format when adding new task.
