### ISSUE TITLE
可以添加一个下载按钮吗？

### ISSUE THREAD

**Issue by wpzzz** [d0u9/youtube-dl-webui#14]
我在vps上安装它，但是视频完成后下载到本地电脑不方便 ，
我目前是把下载目录设置在apache站点目录中，视频下载到vps后再去站点下载到本地
建议在视频done之后出现一个视频超链接 方便下载到本地

**Comment by d0u9** [comment]
Flask is single threaded. I tried to implement such function but failed. It it better to handle download task to nginx or samba service. I personally use samba.
