### ISSUE TITLE
I just wonder how to remove it :p

### ISSUE THREAD

**Issue by naore** [d0u9/youtube-dl-webui#18]
Maybe it's better to use docker?

**Comment by d0u9** [comment]
There is a docker image already, try this: https://hub.docker.com/r/d0u9/youtube-dl-webui/

If you install via `python setup.py install`, [This](https://stackoverflow.com/questions/1550226/python-setup-py-uninstall?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) thread will help you.
