### ISSUE TITLE
docker support shadowsocks client?

### ISSUE THREAD

**Issue by EruditePig** [d0u9/youtube-dl-webui#21]
First, Thank you for your work!

I have  a VPS run shadowsocks server in USA. And I want to run the youtube-dl-webui docker in my NAS(I am in China, inside GFW). can you figure me out how to use the youtube-dl-webui through Shadowsocks client?

I am not so familiar with docker. I googled  and I thought I should  edit the dockerfile, and add Shadowsocks client in to the image.

Am I right? or are there other solutions?

Thank you again!

**Comment by kolonuk** [comment]
I suspect that a VPN would work better than a SOCKS proxy, plus the data would be encrypted...

On the other hand, youtube-dl can specify a SOCKS proxy in the config - see https://github.com/rg3/youtube-dl#options

**Comment by d0u9** [comment]
Of course, youtube-dl-webui does support socks proxy. see https://github.com/d0u9/youtube-dl-webui/blob/master/example_config.json.

What you need to do is:

1. create a new bridge network in your docker.
2. run shadowsocks container under the newly created network.
3. Config your youtube-dl-webui to use the proxy supplied by shadowsocks container.

Also, I have shadowsocks-libev and shadowsocks+kcptun docker imange available online. check it here https://hub.docker.com/r/d0u9/shadowsocks-libev and https://hub.docker.com/r/d0u9/shadowsocks_kcptun
