### ISSUE TITLE
Unreliable connection to backend

### ISSUE THREAD

**Issue by kolonuk** [d0u9/youtube-dl-webui#23]
Firstly, good effort and thanks for this - very useful!

My problem is that I've installed your docker container (dev) and created my own docker container (latest release 0.2.2), but in both instances:

1. list fails to update stats after about a minute
2. config options sometimes empty
3. after multiple browser refreshes, the server fails to respond (ie timeouts)

Looking at the htop, I can see a growing tree of python youtube-dl-webui threads, but very little cpu usage.

Looking at Chrome's debug (F12), there is a growing queue of "list" api endpoint calls all "queued", but none succeeding.

Is this a docker issue in general, or a problem that this is unreliable at present?

I would take a look at the source to try to solve, but my python is very limited, and I only touched on flask development, so not sure where to start.

**Comment by d0u9** [comment]
Test source code installation directly. I haven't take care of this project for months due to my busy daily job. Some problems exits and some enhancements is needed. I will do more tests in my spare time. If you luckily have time to help to contribute, I will appreciate.  :)

**Comment by kolonuk** [comment]
I'll try and check out the code later this week, and see if I can work out what it's doing!

If you want, you can close this down.
