### ISSUE TITLE
Unraid

### ISSUE THREAD

**Issue by bbakermmc** [d0u9/youtube-dl-webui#24]
Can you make a docker for unraid?

**Comment by d0u9** [comment]
Doesn't unraid support standard docker image?

**Comment by bbakermmc** [comment]
You need a specific unraid config file so you can configure the variables from the ui, then I assume maybe you can use a standard docker file.  But no idea.

Sent from my iPhone

On Aug 19, 2018, at 10:53 PM, Douglas Su <notifications@github.com<mailto:notifications@github.com>> wrote:


Doesn't unraid support standard docker image?

**Comment by d0u9** [comment]
Sorry, my friends and I don't have such environment for testing..
