### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by hamidfzm** [d0u9/youtube-dl-webui#29]
Hey,
I had some nice UI changes to this project I wanted to create a pull request. But the last commit on this project was 10 months ago. Do you still accept PRs?

**Comment by d0u9** [comment]
Yes, I still maintain this project. However, after I joined another company, less spare time is owned.

Also, the font end of this project is a mess, refactor is needed.

**Comment by floviolleau** [comment]
Hi,

I know it is an quite old issue but @hamidfzm can you please share your changes?

Thanks!
