### ISSUE TITLE
Hangs when downloading large videos

### ISSUE THREAD

**Issue by wanjeonhanhwang** [d0u9/youtube-dl-webui#6]
I use the docker image.
When downloading large videos, the webui hangs.
I can see in the filesystem that it is downloading. Once finished downloading, it also renames the file from X.mp4.part to X.mp2. The webui reports "Network connection lost". The docker instance has to be restarted before the webui can be used again.

How to reproduce:
1. Click on add button
2. Use this link: https://www.youtube.com/watch?v=S0QHyolErqc
3. Verify that name, total size, progress, down speed and eta is not updated.
4. Try click on other filters to change view. Register that the webui does not change.
5. Observe red information box down right saying "Network connection lost".

**Comment by d0u9** [comment]
I fixed the problem last day, Please try the latest docker image. Sorry for my late reply.

**Comment by d0u9** [comment]
Please reopen this issue if the problem still exists.

**Comment by toanhoang** [comment]
It seems to work. Thanks!
