### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by jiangjiangflies** [d0u9/youtube-dl-webui#7]
There is no config file  in /etc directory and no database file. If I use create these two files myself and an error "sqlite3.OperationalError: no such table: task_status" occurs. I'm using Python3.6.2. Plus I don't why there should be database needed at all.
Thanks for your hardwork!

**Comment by d0u9** [comment]
Which version are you using? I test the latest version of master branch, and it works fine.

**Comment by jiangjiangflies** [comment]
I'm using the latest youtube-dl-webui. Maybe I'm confused by multiple Python versions on my server. The default python3 version is python3.5 so I manually installed python3.6 and then I used` python3.6 setup.py install `to  install youtube-dl-webui. Now the full output error is 
```
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl-webui", line 11, in <module>
    load_entry_point('youtube-dl-webui==0.1.dev0', 'console_scripts', 'youtube-dl-webui')()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl_webui-0.1.dev0-py3.5.egg/youtube_dl_webui/__init__.py", line 26, in main
    core = Core(args=cmd_args)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl_webui-0.1.dev0-py3.5.egg/youtube_dl_webui/core.py", line 49, in __init__
    self.launch_unfinished()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl_webui-0.1.dev0-py3.5.egg/youtube_dl_webui/core.py", line 67, in launch_unfinished
    tlist = self.db.get_unfinished()
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl_webui-0.1.dev0-py3.5.egg/youtube_dl_webui/db.py", line 48, in get_unfinished
    (state_index['finished'], state_index['invalid']))
sqlite3.OperationalError: no such table: task_status
```
which is obviously caused by python3.5. It always becomes so tricky when there are multiple python versions.

**Comment by d0u9** [comment]
I highly recommend you to use [pyenv][1] for managing various versions  of python.

Also, you needn't to create `.db` file manually, it will be automatically created if it doesn't exist. For debugging purpose, it is good to specify the configuration `json` file by `-c` option.

[1]: https://github.com/pyenv/pyenv

**Comment by jiangjiangflies** [comment]
Thanks!  I'll try pyenv and update this thread later.

**Comment by jiangjiangflies** [comment]
Hi, I have tried pyenv but I still got this error in python3.6.2
```
pid is 1895
-----------------------------------
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.2/bin/youtube-dl-webui", line 11, in <module>
    load_entry_point('youtube-dl-webui==0.1.dev0', 'console_scripts', 'youtube-dl-webui')()
  File "/root/.pyenv/versions/3.6.2/lib/python3.6/site-packages/youtube_dl_webui-0.1.dev0-py3.6.egg/youtube_dl_webui/__init__.py", line 26, in main
    core = Core(args=cmd_args)
  File "/root/.pyenv/versions/3.6.2/lib/python3.6/site-packages/youtube_dl_webui-0.1.dev0-py3.6.egg/youtube_dl_webui/core.py", line 38, in __init__
    self.db = DataBase(self.conf['db_path'])
  File "/root/.pyenv/versions/3.6.2/lib/python3.6/site-packages/youtube_dl_webui-0.1.dev0-py3.6.egg/youtube_dl_webui/db.py", line 29, in __init__
    conn = sqlite3.connect(db_path)
sqlite3.OperationalError: unable to open database file
```

**Comment by d0u9** [comment]
Well, I have updated the source, try it again. Please delete the `.db` file firstly to avoid any potential problem.

**Comment by jiangjiangflies** [comment]
Still cannot work. It's the same result. Maybe there is something wrong with the process of my installation?

**Comment by d0u9** [comment]
Below is the detailed process of my installation on xubuntu 16.04:

1. Clone this repo

   git clone https://github.com/d0u9/youtube-dl-webui.git
   cd youtube-dl-webui

2. Create a new virtual environment for testing purpose

   pyenv virtualenv 3.6.1 youtube-test
   pyenv local youtube-test
   pip install flask youtube-dl

3. Install

   python setup.py install

4. Run with the sample configuration file

   youtube-dl-webui -c example_config.json

   The sample configuration file is included in the [source file](https://github.com/d0u9/youtube-dl-webui/blob/master/example_config.json).

**Comment by jiangjiangflies** [comment]
I tried again with no luck. The same error occurs `sqlite3.OperationalError: unable to open database file`.

**Comment by d0u9** [comment]
Can you paste your configuration file here? It is really weird.

**Comment by jiangjiangflies** [comment]
I actually used the example config json file. I only removed the proxy

{                                                          
    "general": {                                           
        "download_dir": "~/Downloads/youtube_dl",          
        "db_path": "~/Documents/youtube_dl_webui.db",      
        "download_log_size": 10                            
    },                                                     
    "server": {                                            
        "host": "0.0.0.0",                                 
        "port": 5000                                       
    },                                                     
    "youtube_dl": {                                        
        "format": "bestaudio/best"                         
    }                                                      
}

**Comment by d0u9** [comment]
In your configuration file, it says that the `.db` file will be located at `/Documents/youtube_dl_webui.db`. However, the `/Documents` directory doesn't exist if you didn't create it before, which in turn makes the error -- `sqlite3.OperationalError: unable to open database file`. The code only creates the `.db` file itself, it won't create the directories containing `.db` file recursively.

In a word, you have to manually create `/Documents` directory before running the code.

**Comment by jiangjiangflies** [comment]
Wow, I was so stupid to think both the directory and db file will be created automatically.  Now it works!  I really thank you for your patience and hard work!

**Comment by EmilMoe** [comment]
Sorry to bring it up again but I'm having the same issue

````
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl-webui", line 11, in <module>
    load_entry_point('youtube-dl-webui===rolling', 'console_scripts', 'youtube-dl-webui')()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl_webui-rolling-py2.7.egg/youtube_dl_webui/__init__.py", line 27, in main
    core.start()
  File "/usr/local/lib/python2.7/dist-packages/youtube_dl_webui-rolling-py2.7.egg/youtube_dl_webui/core.py", line 293, in start
    except PermissionError:
NameError: global name 'PermissionError' is not defined
````

This is my config

````
{
    "general": {
        "download_dir": "/home/pi/Desktop/youtube_dl",
        "db_path": "/tmp/youtube_dl_webui.db",
        "log_size": 10
    },
    "server": {
        "host": "0.0.0.0",
        "port": 5000
    },
    "youtube_dl": {
        "format": "bestaudio/best",
        "proxy": "socks5://127.0.0.1:1080"
    }
}
````

**Comment by notDavid** [comment]
I got the error `sqlite3.OperationalError: unable to open database file` too;

Putting the config file in `/etc/youtube-dl-webui.conf` does not work for me.

You have to run it with `youtube-dl-webui -c /etc/youtube-dl-webui.conf`.
